name = "ActiveFlux"
uuid = "3eef844c-19b3-4909-97d0-cb95cb83af8d"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
KitBase = "86eed249-3a28-466f-8d3a-596821e1af9a"

[compat]
KitBase = "0.9"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]